# Generated by Django 2.1.3 on 2018-12-17 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mof',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lcd', models.FloatField()),
                ('pld', models.FloatField()),
                ('area', models.FloatField()),
                ('density', models.FloatField()),
                ('formula', models.CharField(max_length=255)),
                ('space_group', models.CharField(max_length=255)),
                ('vol_frac', models.FloatField()),
                ('fingerprint', models.ImageField(blank=True, upload_to='comm_contrib')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_publish', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A', to='mof_network.Mof'),
        ),
        migrations.AddField(
            model_name='connection',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B', to='mof_network.Mof'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mof_network.Mof'),
        ),
    ]
